;
; This .ini is a sample to show how to set up different examples
;
; By Eligio Sacateca, May 2003
;
; Instructions
; Specify the number of transform groups with ntransforms.
; The program will only read this many transforms even if
; you include more in this file.
;
; For each transform, create an index row [s<transform#>]
; These do not have to be in order (altho they are easier
; to keep track of if they are, obviously).
;
; If you skip a row the corresponding group will not match
; any input files so it should not hurt anything (it won't
; help either but if you delete one you don't need to go
; back and renumber everything).
;
; 
; The format of each group is:
; match= : if this string matches the input source model name, this
;     group will be applied against the input file to produce an
;     output file. This string uses globbing where a '?' is a wildcard
;     and will match any single character while '*' is a full glob
;     wildcard and will match any number of characters. Examples:
;       abc* matches abcdef
;       abc??? matches abcdef but not abcdefg
;       abc*f matches abcdef and abcdeanythingf
;       abc does not match abcdef
;
; substitute= : the file and model name of the new file will consist
;     of the input name, modified by substituting characters in this 
;     string against it. a '?' is a wildcard and will not change the
;     input string at that point. A '*' is a full glob wildcard and
;     will not change any more characters past the end of the input
;     name. If the input model name exceeds the substitute string in
;     length (after taking into consideration wild cards like '?' and
;     '*'), excess characters will be truncated. If the input model
;     is shorter, extra characters from the substitute string will be
;     appended at the end. Examples:
;       abcnopqrs to defghi gives abcnopqrs
;       abc to defghi gives abc
;       abc? to defghi gives abcg
;       abc* to defghi gives abcghi
;       abc*n to defghi gives abcghin
;       ??abc to defghi gives deabc
;
; scale=(x, y, z) : x, y and z axis scaling respectively. If you 
;     don't put in a scale parameter for a group, it defaults
;     to (1, 1, 1) (i.e., no scaling).
;
; rotate=(x, y, z) : x, y, and z axis rotation respectively. If
;     you don't put in a rotate parameter for a group, it defaults
;     to (0, 0, 0) (i.e., no rotation).
;
; translate=(x, y, z) : x, y, and z axis translation respectively. If
; you don't put in a translate parameter for a group, it defaults
; to (0, 0, 0) (i.e., no translation).
; This is a parameter with absolute values so don't forget
; that most models are scaled by 100x when viewing them in Gmax or
; Max - if you experiment in these tools to get the right values,
; don't forget to reduce translations appropriately.
;
; position=(x, y, z) : x, y, and z axis specification for the position
; parameter within the model file. For armor parts, the position
; parameter identifies the pivot point for the model.
; This is a parameter with absolute values so don't forget
; that most models are scaled by 100x when viewing them in Gmax or
; Max - if you experiment in these tools to get the right values,
; don't forget to reduce translations appropriately.
;
; minimum=(x, y, z) : if a vertex is outside of the minimum
; x, y, and z values, it will not be transformed. I don't expect
; this and the maximum= parameters to be used much but they can
; be set up to do selective transforms on vertices. I created
; these parameters so that I could scale parts of a model differently
; than the rest of the model.
; This is a parameter with absolute values so don't forget
; that most models are scaled by 100x when viewing them in Gmax or
; Max - if you experiment in these tools to get the right values,
; don't forget to reduce translations appropriately.
;
; maximum=(x, y, z) : if a vertex is outside of the maximum
; x, y, and z values, it will not be transformed.
; This is a parameter with absolute values so don't forget
; that most models are scaled by 100x when viewing them in Gmax or
; Max - if you experiment in these tools to get the right values,
; don't forget to reduce translations appropriately.
;
; If the scale, rotate, and translate parameters amount to no
; no change, the program will just copy the input file and rename
; the model according to the substitute string. This is useful for
; copying and renaming models with no other changes.
;
;
; trotate=(z) : (new!) z-axis rotation of the texture map. If
; you don't put in a rotate parameter for a group, it defaults
; to (0) (i.e., no rotation).
;
; tscale=(x, y): (new!) x and y axis scaling respectively for a
; texture map. If you don't put in a scale parameter for
; a group, it defaults to (1, 1) (i.e., no scaling).
;
; ttranslate=(x, y) : (new!) x and y axis translation of your texture
; map, respectively (that's right, you can now move texture maps around).
; If you don't put in a translate parameter for a group, it defaults
; to (0, 0, 0) (i.e., no translation).
; This is a parameter with absolute values so don't forget
; that most models are scaled by 100x when viewing them in Gmax or
; Max - if you experiment in these tools to get the right values,
; don't forget to reduce translations appropriately.
;
; tminimum=(x, y) : (new!) if a texture vertex is outside of the
; minimum x and y values, it will not be transformed. These is
; pretty much the same as the minimum and maximum values applied
; to texture maps.
;
; tmaximum=(x, y) : (new!) if a vertex is outside of the maximum
; maximum x and y values, it will not be transformed.
;
; tbitmap=<bitmap name> : (new!) lets you specificy that only texture maps
; for this bitmap will be transformed.
; 
; That's it!


[Global]
SourceDir=D:\Current\Custom\Armory\NWNArmory\TestIn
DestDir=D:\Current\Custom\Armory\NWNArmory\TestOut
LogFileName=D:\Current\Custom\Armory\NWNArmory\TestOut\NWNArmory.Log

; level 1 = basic, level 2 = debug mode
LogLevel=1

; make sure you set this! set it to one higher than the last [sN]
nTransforms=8

; copy example
[s0]
match=pf??_chest*
substitute=??a0*

; another explicity copy example
; matches female belt models (* at the end matches 001, 002, etc.)
[s1]
match=pF??_belt*
substitute=??a0
Scale=(1,1,1.0)
Rotate=(0,0,0)

; scale in all directions by 2x
; matches female belt models (??? at the end also matches 001, 002, etc.)
[s2]
match=pf??_belt???
substitute=??b0*
Scale=(2.0, 2.0, 2.0)
Rotate=(0.0, 0.0, 0)

; rotate 40 degrees around x-axis followed by 30 degree rotation around y-axis
; but no scaling
[s3]
match=pf??_belt*
substitute=??c0_abcdefghijklmn
Scale=(1.0, 1, 1)
Rotate=(40, 30.0, 0 )

; scale and rotate example
[s4]
match=pf??_chest*
substitute=??b0
Scale=(2.0, 1.1, 1)
Rotate=(40, 30.0, 0 )

; won't match anything so won't do anything
[s5]


; scale and rotate example
[s6]
match=pf??_belt*
substitute=??d0
Scale=(1,1,1)
Rotate=(25, 10.0, 50 )
minimum=(1,2,4)
maximum=(3,3,8)

; texture map example
[s7]
match=wswdg_?_01*
substitute=wswdg_?_04
tscale=(0.75,0.2)
trotate=(90)
ttranslate(0.1, 0.1)
tminimum=(0.1,0.1)
tmaximum=(0.8,0.8)

